// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/about.tsx";
import * as $1 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/TextFlicker.tsx";
import * as $$2 from "./islands/ThreeCanvas.jsx";
import * as $$3 from "./islands/TimeCounter.tsx";

const manifest = {
  routes: {
    "./routes/about.tsx": $0,
    "./routes/index.tsx": $1,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/TextFlicker.tsx": $$1,
    "./islands/ThreeCanvas.jsx": $$2,
    "./islands/TimeCounter.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
