// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $index from "./routes/index.tsx";
import * as $Preview from "./islands/Preview.tsx";
import * as $SplineBackdrop from "./islands/SplineBackdrop.tsx";
import * as $terminal_History from "./islands/terminal/History.tsx";
import * as $terminal_Terminal from "./islands/terminal/Terminal.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_layout.tsx": $_layout,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Preview.tsx": $Preview,
    "./islands/SplineBackdrop.tsx": $SplineBackdrop,
    "./islands/terminal/History.tsx": $terminal_History,
    "./islands/terminal/Terminal.tsx": $terminal_Terminal,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
