// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_layout from "./routes/_layout.tsx";
import * as $home_guest_guest from "./routes/home/guest/guest.tsx";
import * as $home_home from "./routes/home/home.tsx";
import * as $index from "./routes/index.tsx";
import * as $History from "./islands/History.tsx";
import * as $Terminal from "./islands/Terminal.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
    routes: {
        "./routes/_404.tsx": $_404,
        "./routes/_app.tsx": $_app,
        "./routes/_layout.tsx": $_layout,
        "./routes/home/guest/guest.tsx": $home_guest_guest,
        "./routes/home/home.tsx": $home_home,
        "./routes/index.tsx": $index,
    },
    islands: {
        "./islands/History.tsx": $History,
        "./islands/Terminal.tsx": $Terminal,
    },
    baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
