/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: ghostlyfail (https://sketchfab.com/ghostlyfail)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/naruto---frog-wallet-70389cbf2bec4b0d813d099633b099f7
title: Naruto _ Frog Wallet
*/

import React from 'react'
import { useFrame } from '@react-three/fiber'
import { useGLTF } from '@react-three/drei'

export default function Model({ body, type, ...props }) {
  const { nodes, materials } = useGLTF('/frog.glb')
  let orbit = 2 * Math.PI * (1 / 60) * (1 / 60);
  let angle = 1/12 * Math.PI;

  switch (type) {
    case 'moon':
      orbit *= -0.035;
      angle = 1/5 * Math.PI;
      break;
    case 'ship':
      orbit *= 3;
      angle = -1/5 * Math.PI;
      break;
    default:
      break;
  }

  useFrame(({ clock }) => {
    body.current.rotation.y += orbit;
    body.current.rotation.x = angle;
  })

  return (
    <group ref={body}>
      <group {...props} dispose={null}>
        <group rotation={[-Math.PI / 2, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            {/* TODO Create kurzgesagt-like models!
            <mesh geometry={nodes} material={materials.Material__2} /> */}
            <mesh>
              <sphereGeometry/>
              <meshLambertMaterial/>
            </mesh>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/frog.glb')
